# Generated by Django 2.2.3 on 2019-07-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_accounts', '0002_auto_20190721_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='last_login_on',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
